###
### mkdocs-site.yml
###
docs_dir: Labs
edit_uri: ""
repo_name: nirgeier/mkdocs
repo_url: https://github.com/nirgeier/mkdocs
site_author: Nir Geier - nirgeier@gmail.com
site_description: A collection of GitHub Labs for learning and practicing GitHub skills.
site_dir: ./mkdocs-site
site_name: mkdocs
site_url: https://nirgeier.github.io/mkdocs/
###
### mkdocs-theme.yml
###
copyright: "Â©2025-2025 Nir Geier"
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - content.footer.last-updated
    - content.footer.contributors
    - navigation.expand: true
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top: true
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    #- header.autohide  # Disabled to keep top nav always visible
    - toc.integrate
  # ðŸ‘ˆ enables avatar display
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # You can choose any color here
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo # You can choose any color here
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Mulish
    code: JetBrains Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    admonition:
      note: material/lightbulb
###
### mkdocs-extra.yml
###

extra:
  assets:
    - ./assets/images/
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nirgeier/mkdocs
      name: View on GitHub
    - icon: octicons/star-16
      link: https://github.com/nirgeier/mkdocs/stargazers
      name: Star this repo
    - icon: octicons/repo-forked-16
      link: https://github.com/nirgeier/mkdocs/network/members
      name: Fork this repo

extra_css:
  - ./assets/stylesheets/theme.css
extra_javascript:
  - https://buttons.github.io/buttons.js
###
### mkdocs-plugins.yml
###

plugins:
  - awesome-pages
  - section-index
  - meta
  # - pdf-export:
  #     combined: true # all pages in one PDF
  #     combined_output_path: docs/Full-Documentation.pdf
  #     media_type: print
  #     verbose: true
  # Git
  - git-authors
  - git-committers:
      branch: main
      docs_path: Labs # set if your docs folder is not root
      enabled: true
      repository: nirgeier/mkdocs
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false
      fallback_to_build_date: true
      locale: en
      timezone: UTC
      type: date
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

  # Leave this one as the last one in the list
  - print-site
###
### mkdocs-extensions.yml
###

markdown_extensions:
  - toc:
      permalink: false
      baselevel: 1
      toc_depth: 3
  - abbr
  - tables
  - admonition # For callouts/notes
  - footnotes # Footnotes support
  - attr_list # Attribute lists for elements
  - def_list # Definition lists
  - md_in_html # Markdown inside HTML blocks
  - smarty # Smart punctuation
  - meta
  - codehilite:
      guess_lang: true # Fallback code highlighting
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details # Collapsible details
  - pymdownx.inlinehilite # Inline code highlighting
  - pymdownx.keys # Keyboard key formatting
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tilde # Subscript/superscript
  - pymdownx.snippets # Snippet includes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
###
### mkdocs-nav.yml
###

nav:
  - Home: tutorials/README.md
  - Tutorials:
    - 000-Setup: tutorials/000-setup/README.md
    - 001-Verify-Cluster: tutorials/001-verify-cluster/README.md
    - 002-New-User: tutorials/002-new-user/README.md
    - 003-New-Project: tutorials/003-new-project/README.md
    - 004-Docker-Lifecycle: tutorials/004-docker-lifecycle/README.md
    - 005-Docker-Pipeline: tutorials/005-docker-pipeline/README.md
    - 006-Hooks-Setup: tutorials/006-hooks-setup/README.md
    - 007-Images-ImageStream: tutorials/007-images-imagestream/README.md
    - 008-Deploying: tutorials/008-deploying/README.md
    - 009-Services-Routes: tutorials/009-services-routes/README.md
    - 010-Monitoring: tutorials/010-monitoring/README.md
    - 011-Logging: tutorials/011-logging/README.md
    - 012-Scaling: tutorials/012-scaling/README.md

